export default {
  Name: 'Chris Chan',
  Birth: '1996-10-30',
  Gender: 'Male',
  Location: 'Guangzhou, Guangdong, China',
  Languages: {
    Chiness: 'Native',
    English: 'CET-6',
  },
  Github: 'https://github.com/ChrisChan13',
  'E-Mail': 'chrischan1213@qq.com',
  'Web-Site': 'https://chrischan13.github.io/wdnmd',
  Certificates: [{
    Time: '2017-01',
    Name: 'CET-6',
  }, {
    Time: '2016-09',
    Name: 'NCRE-2 Java',
  }],
  Educations: [{
    Duration: '2015-09 ~ 2018-07',
    University: 'GDAIB',
    Major: 'Software Technology',
  }, {
    Duration: '2015-09 ~ 2018-07',
    University: 'SCUT',
    Major: 'Digital Media Arts',
  }],
  Skills: [
    'JavaScript',
    'HTML',
    'CSS',
    'Node.js',
    'Vue.js',
    'JSX',
    'SASS',
    'LESS',
    'MiniProgram',
    'React.js',
    'Nuxt.js',
    'Next.js',
    'Koa.js',
    'TypeScript',
    'MongoDB',
  ],
};
